
library(tm)
library(tidyverse)
data <- read.csv("tango_lyrics.csv", sep=";")
lyrics<-Corpus(VectorSource(data$lyric))
lyrics <- tm_map(lyrics, content_transformer(tolower))
lyrics <- tm_map(lyrics, removeNumbers)
lyrics <- tm_map(lyrics, removeWords, stopwords("spanish"))
lyrics <- tm_map(lyrics, removePunctuation)
lyrics <- tm_map(lyrics, stripWhitespace)
lyrics_dtm <- DocumentTermMatrix(lyrics)
m <- as.matrix(lyrics_dtm)
f <- sort(colSums(m), decreasing = TRUE)
d <- data.frame(words=names(f), freq=f)
write.csv(head(d,10), file="freq.csv", row.names = F)
